#!/usr/bin/env python3
import json, subprocess, sys, tempfile
from pathlib import Path
root=Path(__file__).resolve().parent
def receipt(action):
 s="x"; return {"schema_version":"workflow-transition-admission-v1","receipt_id":"r","objective_id":"o","source_sha256":"0"*64,"owner_role":"WORKER","action_class":action,"requested_transition":"EXECUTE","material_candidate_action":True,"released_external_action":False,"correction_admission":{"applicable":True,"authority_mode":"EXACT_SOURCE","authority_ref":s,"fcr_status":"CLOSED","fcr_ref":s,"scenario_status":"FROZEN","scenario_ref":s,"interaction_ids":[s],"impact_status":"PLANNED","impact_ref":s,"omission_consequence":s,"expected_objective_delta":s,"cost_rework_counterfactual":s,"return_step":s},"known_cause":{"applicable":False,"global_master_search_ref":s,"project_master_search_ref":s,"signature":s,"disposition":s,"prior_family_ref":s,"changed_premise":s,"discriminating_prediction":s},"skill_effect":{"applicable":False,"action_finalized":False,"selected_ref":"","bytes_ref":"","script_applicable":False,"script_ref":"","application_ref":"","effect_ref":"","repeated_mechanical_family":False,"constrained_representation":False},"freshness":{"required":False,"observed_at":s,"state_ref":s,"dependent_claim_ids":[],"baseline_status":"NOT_APPLICABLE"},"monitoring":{"applicable":False,"decision_window_ref":"","cursor_status":"NOT_APPLICABLE","objective_evidence_delta":"","unchanged_reuse":False,"progress_status":"NOT_APPLICABLE","wait_value_ref":"","fixed_polling":False,"recovery_disposition":""},"stage_allocation":{"job_shape_changed":False,"view_ref":"","disposition":""},"value":{"auxiliary":False,"mandatory_outcome_unproven_if_omitted":s,"expected_time_saved":s,"retirement_condition":s},"topology":{"supervisor_internal_implementer":False,"read_only_auditor":False,"implementing_owner_role":"FORMAL_WORKER","formal_worker_task_ref":s,"recovery_mode":"NORMAL"},"scenario_recomposition":{"applicable":True,"semantic_lock_ref":s,"relation_ids":[s],"witness_ref":s,"unresolved_relation_ids":[]},"consumer":{"required":True,"outcome_claim_ids":[s],"oracle_ref":s,"evidence_delta":s,"status":"UNPROVEN"},"proof_ceiling":s}
with tempfile.TemporaryDirectory() as d:
 for action in ("finalized_dependent_action","commit_push","ci_dispatch","external_apply"):
  value=receipt(action)
  if action=="external_apply": value["released_external_action"]=True;value["freshness"]={"required":True,"observed_at":"now","state_ref":"state","dependent_claim_ids":["claim"],"baseline_status":"CURRENT"}
  p=Path(d)/(action+".json");p.write_text(json.dumps(value),encoding="utf-8");assert subprocess.run([sys.executable,"-B",str(root/"transition_admission.py"),"--input",str(p)]).returncode==0
 blocked=receipt("finalized_dependent_action");blocked["correction_admission"]["scenario_status"]="MISSING";p=Path(d)/"bypass.json";p.write_text(json.dumps(blocked),encoding="utf-8");assert subprocess.run([sys.executable,"-B",str(root/"transition_admission.py"),"--input",str(p)]).returncode!=0
 blocked=receipt("external_apply");blocked["released_external_action"]=False;p=Path(d)/"external-bypass.json";p.write_text(json.dumps(blocked),encoding="utf-8");assert subprocess.run([sys.executable,"-B",str(root/"transition_admission.py"),"--input",str(p)]).returncode!=0
 print("v14 material transition actions passed")
